[package]
name = "zyn-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
once_cell = "1.21.3"
regex = "1.12.2"
zyn-protocol-macros = { path = "../zyn-protocol-macros" }
zyn-util = { path = "../zyn-util" }
